# Generated by Django 3.2.16 on 2022-12-26 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('createdbymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.createdbymodel')),
                ('name', models.CharField(max_length=512)),
            ],
            bases=('core.createdbymodel',),
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('createandupdatemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.createandupdatemodel')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chatgroup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.createandupdatemodel',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('createandupdatemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.createandupdatemodel')),
                ('text', models.CharField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.groupmember')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.message')),
            ],
            bases=('core.createandupdatemodel',),
        ),
    ]
